### PR TITLE
Add debugging options

### LINKED ISSUE #1: Add debugging options
The following debugging options should be added 

1. `maxConcurrency`
2. `maxPendingConnectionAcquires`  
3. `maxConnection` 
4. enable wire logging for the SDK

Those settings should be provided either via env vars or java system properties

### References 

* https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html#setting-maximum-connections
* https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setMaxConnections-int-
* https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

### PR DESCRIPTION
**Pull request by jordeu**
## Description

- [x] Add max connections setting using  `AWS_MAX_CONNECTIONS` environment var or `aws.max_connections` java property
- [x] Add SDK v2 transfer manager 
- [x] Add max concurrency at SDK v2. 
- [x] Enable wire logging for the SDK. Use `AWS_LOG_LEVEL = DEBUG`

### CODE REVIEW

**Comment by HLWiencko** [comment]
@jordeu This has been waiting for review for a while. Can we close it?

**Comment by jordeu** [comment]
@HLWiencko, do you mean the PR or the repo?

If you mean the PR, it may still be worth merging because, on platform and Nextflow, as far as I know, they are still using AWS Java SDK v1 in some cases.

This PR added the option to test both SDK v1 and v2. 

@pditommaso @bentsherman, do you think it is worth merging?

**Comment by HLWiencko** [comment]
@jordeu I meant the PR! If it's useful, let's get it merged.

**Comment by bentsherman** [comment]
Benchmarking SDK v1 and v2 outside of Nextflow would be very useful for us

**Pull request merged**
